### ISSUE TITLE
[BUG] CertificateAvailable event is being triggered for units that already received it

### ISSUE THREAD

**Issue by paulomach** [canonical/tls-certificates-operator#34]
**Describe the bug**

Given the scenario: 3 unit app A related to tls-certs charm and all is fine.
The on.certificate_available handle on app A test it own `csr` against the incoming event `csr` and being it the same, enable TLS for the workload queuing it to a rolling restart.

The issue appears when one or more units are added to app A.
For each new unit added, the existing units are going to receive a `CertificateAvailable` event, with a valid `csr` per unit, triggering an unnecessary workload restart.

**To Reproduce**

1. deploy tls-certificates-operator and mysql-k8s
2. relate applications and wait for idle
3. scale up mysql-k8s by n units
4. observe `CertificateAvailable` being triggered for the units deployed before the scale out

**Expected behavior**
Only new n units should receive `CertificateAvailable` event.

**Environment**
 - tls-certificates-interface library version: 1.12
 - Juju version: 2.9.38
 - Cloud Environment: localhost
 - Kubernetes version: microk8s 1.26.1

**Comment by gruyaume** [comment]
Thank you @paulomach for filing this issue. It is indeed a bug and should have been supported. This will require a new major version of the lib and we will address it during our next pulse.

Reference:
- https://warthogs.atlassian.net/browse/TELCO-394

**Comment by gruyaume** [comment]
I believe this bug is caused by the fact that given a CSR in the requirer unit databag when the provider adds a certificate to the relation data, there is no way for the requirer lib to know which certificate was added by the provider and which one was already there. So, we go through each CSR in the requirer's relation data and check if there is a match with the certificate and if yes, we trigger CertificateAvailable. 

We'll have to dig a bit deeper to confirm this.

**Comment by gruyaume** [comment]
I am unaware of a design that would address this behavior **and** not require to store the state of the relation databag. I'm open to ideas though.

**Comment by paulomach** [comment]
@gruyaume , I understand the constraints there and I'm ok with it. 
Going forward I agree that improving the interface documentation would help.
As reference, we added a control flag on unit peer databag to workaround this behavior (see [here](https://github.com/canonical/mysql-operator/blob/eeaf55b22c3073d816afce24eae5ca04e62619ba/src/relations/mysql_tls.py#L86), [here](https://github.com/canonical/mysql-operator/blob/eeaf55b22c3073d816afce24eae5ca04e62619ba/src/relations/mysql_tls.py#L108) and [here](https://github.com/canonical/mysql-operator/blob/eeaf55b22c3073d816afce24eae5ca04e62619ba/src/relations/mysql_tls.py#L168) for reference.
Feel free to close up this bug.

**Comment by gruyaume** [comment]
Ok great, we'll close the bug once the docs are updated
