### ISSUE TITLE
[BUG] spelling typos in shared library triggers lint error

### ISSUE THREAD

**Issue by taurus-forever** [canonical/tls-certificates-operator#35]
**Describe the bug**

Our codespell lint is [not happy](https://github.com/canonical/kafka-bundle/actions/runs/4373173395/jobs/7651007585#step:4:9) after updating to TLS library to LIBPATCH 12:

```
.../tls_certificates_interface/v1/tls_certificates.py:1025: triggerred ==> triggered
.../tls_certificates_interface/v1/tls_certificates.py:1068: agains ==> against, again
```

Can you please fix typos? Maybe consider to add [codespell](https://github.com/canonical/mysql-operator/blob/main/tox.ini#L49) to your [lint](https://github.com/canonical/tls-certificates-operator/blob/main/tox.ini#L33). Thank you!

**Comment by gruyaume** [comment]
@taurus-forever Unfortunately [this bug with snapcraft](https://github.com/canonical/charmcraft/issues/1020) makes it impossible to update the v1 of the lib. 

[This PR](https://github.com/canonical/tls-certificates-interface/pull/50) will fix the issue in v2 of the lib and once it is merged I'll create a PR here to bump the lib.
