### ISSUE TITLE
[BUG]Action parameters may be broken

### ISSUE THREAD

**Issue by gtrkiller** [canonical/tls-certificates-operator#52]
**Describe the bug**
The charm does not have good parameters for its actions. When trying to execute an action, there is an error in validation because the parameter have underscores in their names (e.g. relation_id) and that throws an error.

**To Reproduce**
1- Execute any action with a parameter that contains an underscore. E.g. `juju run tls-certificates-operator/0 get-outstanding-certificate-requests relation_id=0`

**Expected behavior**
The action should execute without any errors.

**Screenshots**
![image](https://github.com/canonical/tls-certificates-operator/assets/54121436/3e6dc9ee-cb61-404b-936e-083b9ce76b80)

**Environment**
 - tls-certificates-interface library version 2.12
 - Juju version: 3.1.5-genericlinux-amd64
 - Cloud Environment: Microk8s cloud
 - Kubernetes version 1.28

**Comment by saltiyazan** [comment]
Hi @gtrkiller 
I am working on the fix right now.
[This is the PR](https://github.com/canonical/tls-certificates-operator/pull/54) to fix it.
Until then a workaround is to use a parameter.yaml file and pass it to the action with `--params parameters.yaml`
