### ISSUE TITLE
[RFE] operator should validate the received certificate and CA chain against each other

### ISSUE THREAD

**Issue by phvalguima** [canonical/tls-certificates-operator#58]
Where the change should be applied: ```tls-certificate-operator``` code (not its lib)

At ```provide-certificate``` action, the current implementation of tls-certificates-operator only validate the certificate itself and each certificate composing the CA chain. However, it does not check if the certificate chain is valid

For that, we should extend [this part of the action](https://github.com/canonical/tls-certificates-operator/blob/main/src/charm.py#L164-L176) to support [verify_directly_issued_by](https://github.com/pyca/cryptography/blob/d7aa76102ad8967b5c56eef89fc9d012fd0851e9/src/rust/src/x509/certificate.rs#L270) method.

If that validation fails, then the action should return an error.

**Comment by patriciareinoso** [comment]
Done in https://github.com/canonical/tls-certificates-operator/pull/69
