### ISSUE TITLE
[RFE] At provide-certificate action, verify public keys in CSR and received certificate matches

### ISSUE THREAD

**Issue by phvalguima** [canonical/tls-certificates-operator#59]
During the processing of ```provide-certificate``` action, the tls-certificates-operator should use the ```relation-id``` provided as a parameter to recover the CSR set by the Requirer and compare main fields: 
```
# Compare types as there are multiple and key values
if not csr.public_key === certificate.public_key:
    event.fail(message="Certificate and CSR public keys do not match")
    return
if csr.subject != certificate.subject:
    event.fail(message=f"Certificate has subject: {certificate.subject} whereas CSR has: {csr.subject}")
    return
```

**Comment by gruyaume** [comment]
This makes sense, I'll add this to our TODO.

**Comment by patriciareinoso** [comment]
https://github.com/canonical/tls-certificates-operator/pull/67 implements this and is merged.
